### ISSUE TITLE
Should suggest a top 10 users 

### ISSUE THREAD

**Issue by DiscoveringWorld** [fre3d0m1/bot-detector#35]
botdetector run
- Initializing.. -
Please enter a username and a category.

**Comment by fre3d0m1** [comment]
That's a good idea, I'll try implementing that.

**Comment by DiscoveringWorld** [comment]
Do you  have any news on that ?

**Comment by DiscoveringWorld** [comment]
Finally I think it's not possible.

Follow what I found, they don't have a possibility to list a top ten users.

https://devforum.roblox.com/t/collected-list-of-apis/557091
