### ISSUE TITLE
Should add some colors

### ISSUE THREAD

**Issue by DiscoveringWorld** [fre3d0m1/bot-detector#46]
example code for colored text:

![image](https://user-images.githubusercontent.com/20508652/103111006-29d54680-4616-11eb-8adf-5850067d23a7.png)

````
from colorama import init
from termcolor import colored

init()

print(colored('Hello, World!', 'yellow'))

**Comment by fre3d0m1** [comment]
Get the version 0.3.2 of the program or later and then try running a command.
